### ISSUE TITLE
LDAP Domain Name

### ISSUE THREAD

**Issue by brunowego** [RiCi12/ldap-laravel-provider#1]
You done a very nice job here, congrats!

My question: You can explain where I find the LDAPDOMAINNAME?

**Comment by RiCi12** [comment]
Hi.

Ldapdomainname is the domain name of your network: usually, the network
admin knows it. It's what you place before the username when you try to
authenticate.

DOMAINNAME\username

Bye.
Il 18/lug/2015 01:39 AM, "Bruno Wego" notifications@github.com ha scritto:

**Comment by brunowego** [comment]
I have this: `ou=people,dc=domain,dc=net`

Sorry for my ignorance regarding LDAP.

**Comment by brunowego** [comment]
@RiCi12 your project is for Active Directory or OpenLDAP (or both)?

**Comment by RiCi12** [comment]
It has been tested only with Active Directory. Never tried with OpenLDAP.

**Comment by brunowego** [comment]
I understand, I am not using AD. So that's why I could not connect. Thank @RiCi12 for trying to help me!

**Comment by RiCi12** [comment]
No problem.
I'm going to modify the README file so it will explain that this is for AD. 

Thank you!

**Comment by brunowego** [comment]
To knowledge of others who want to connect with OpenLDAP, this package works for me: https://github.com/maen-bn/ldaplookup

Thanks again @RiCi12 :+1:
